// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.5.0
// source: appid_service.proto

package appid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting public key by app ID
type GetPublicKeyByAppIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyByAppIDRequest) Reset() {
	*x = GetPublicKeyByAppIDRequest{}
	mi := &file_appid_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyByAppIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyByAppIDRequest) ProtoMessage() {}

func (x *GetPublicKeyByAppIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appid_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyByAppIDRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyByAppIDRequest) Descriptor() ([]byte, []int) {
	return file_appid_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicKeyByAppIDRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// Response message for getting public key by app ID
type GetPublicKeyByAppIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publickey     string                 `protobuf:"bytes,1,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Curve         string                 `protobuf:"bytes,3,opt,name=curve,proto3" json:"curve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyByAppIDResponse) Reset() {
	*x = GetPublicKeyByAppIDResponse{}
	mi := &file_appid_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyByAppIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyByAppIDResponse) ProtoMessage() {}

func (x *GetPublicKeyByAppIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appid_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyByAppIDResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyByAppIDResponse) Descriptor() ([]byte, []int) {
	return file_appid_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicKeyByAppIDResponse) GetPublickey() string {
	if x != nil {
		return x.Publickey
	}
	return ""
}

func (x *GetPublicKeyByAppIDResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *GetPublicKeyByAppIDResponse) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

// Error response structure
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_appid_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appid_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_appid_service_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_appid_service_proto protoreflect.FileDescriptor

const file_appid_service_proto_rawDesc = "" +
	"\n" +
	"\x13appid_service.proto\x12\x05appid\"3\n" +
	"\x1aGetPublicKeyByAppIDRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"m\n" +
	"\x1bGetPublicKeyByAppIDResponse\x12\x1c\n" +
	"\tpublickey\x18\x01 \x01(\tR\tpublickey\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05curve\x18\x03 \x01(\tR\x05curve\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2l\n" +
	"\fAppIDService\x12\\\n" +
	"\x13GetPublicKeyByAppID\x12!.appid.GetPublicKeyByAppIDRequest\x1a\".appid.GetPublicKeyByAppIDResponseB\n" +
	"Z\b./;appidb\x06proto3"

var (
	file_appid_service_proto_rawDescOnce sync.Once
	file_appid_service_proto_rawDescData []byte
)

func file_appid_service_proto_rawDescGZIP() []byte {
	file_appid_service_proto_rawDescOnce.Do(func() {
		file_appid_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appid_service_proto_rawDesc), len(file_appid_service_proto_rawDesc)))
	})
	return file_appid_service_proto_rawDescData
}

var file_appid_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_appid_service_proto_goTypes = []any{
	(*GetPublicKeyByAppIDRequest)(nil),  // 0: appid.GetPublicKeyByAppIDRequest
	(*GetPublicKeyByAppIDResponse)(nil), // 1: appid.GetPublicKeyByAppIDResponse
	(*ErrorResponse)(nil),               // 2: appid.ErrorResponse
}
var file_appid_service_proto_depIdxs = []int32{
	0, // 0: appid.AppIDService.GetPublicKeyByAppID:input_type -> appid.GetPublicKeyByAppIDRequest
	1, // 1: appid.AppIDService.GetPublicKeyByAppID:output_type -> appid.GetPublicKeyByAppIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_appid_service_proto_init() }
func file_appid_service_proto_init() {
	if File_appid_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appid_service_proto_rawDesc), len(file_appid_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appid_service_proto_goTypes,
		DependencyIndexes: file_appid_service_proto_depIdxs,
		MessageInfos:      file_appid_service_proto_msgTypes,
	}.Build()
	File_appid_service_proto = out.File
	file_appid_service_proto_goTypes = nil
	file_appid_service_proto_depIdxs = nil
}
